### PR TITLE
Updated the README file.

### PR DESCRIPTION
**Pull request by therealmrmuffin**
I updated the README file to make it look much more sleeker.

### CODE REVIEW

**Review by nguyenkims — COMMENTED** [review]
I'd keep the section on how to run the code locally (maybe moved it to the bottom?) so other people can run the doc locally. This is useful for testing out changes that affect the template for example.

**Comment by therealmrmuffin** [comment]
> I'd keep the section on how to run the code locally (maybe moved it to the bottom?) so other people can run the doc locally. This is useful for testing out changes that affect the template for example.

That's a great idea indeed! I removed it, because i tough it was a default thing everybody did. But i guess i was wrong. 😅

**Comment by therealmrmuffin** [comment]
@nguyenkims Added the section back below as requested.

**Review by nguyenkims — APPROVED** [review]
Looks good to me!

**Pull request merged**
